# Generated by Django 4.0.2 on 2022-02-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=70)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('card_number', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/users/%Y/%m/%d')),
            ],
        ),
    ]
